### ISSUE TITLE
BundleException: Unresolved requirement: Import-Package: com.sforce.soap.partner

### ISSUE THREAD

**Issue by ScarleTAKE** [amusarra/salesforce-client-soap#7]
hi 

liferay ce version 7.4 ga 11
jdk: 1.8

i try modify build.gradle with:
compile group: 'it.dontesta.labs.liferay.salesforce.client.soap', name: 'salesforce-client-soap', version: '1.2.0'
and got exception after deploy

2022-03-07 02:39:00.782 ERROR [Framework Event Dispatcher: Equinox Container: 1390521e-ba98-4ac6-b458-171ce584ab47][Framework:93] FrameworkEvent ERROR 
com.liferay.portal.kernel.log.LogSanitizerException: org.osgi.framework.BundleException: Could not resolve module: com.raritan.ci.pqm.api [1492]_  Unresolved requirement: Import-Package: com.sforce.soap.partner; version="[1.0.0,2.0.0)"_ [Sanitized]
	at org.eclipse.osgi.container.Module.start(Module.java:444) ~[org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1682) ~[org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1662) ~[org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1624) ~[org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.container.SystemModule.startWorker(SystemModule.java:264) ~[org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.container.Module.doStart(Module.java:581) ~[org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.container.Module.start(Module.java:449) ~[org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.container.SystemModule.start(SystemModule.java:188) ~[org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:428) ~[org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:447) ~[org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.launch.Equinox.start(Equinox.java:115) ~[org.eclipse.osgi.jar:?]
	at com.liferay.portal.bootstrap.ModuleFrameworkImpl.startFramework(ModuleFrameworkImpl.java:244) ~[com.liferay.portal.bootstrap.jar:?]
	at com.liferay.portal.module.framework.ModuleFrameworkUtil.startFramework(ModuleFrameworkUtil.java:45) ~[portal-impl.jar:?]
	at com.liferay.portal.spring.context.PortalContextLoaderListener.contextInitialized(PortalContextLoaderListener.java:290) ~[portal-impl.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_202]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_202]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_202]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_202]
	at com.liferay.shielded.container.internal.proxy.ContextClassLoaderInvocationHandler.invoke(ContextClassLoaderInvocationHandler.java:43) ~[com.liferay.shielded.container.impl.jar:?]
	at com.liferay.shielded.container.internal.proxy.EventListenerInvocationHandler.invoke(EventListenerInvocationHandler.java:64) ~[com.liferay.shielded.container.impl.jar:?]
	at com.sun.proxy.$Proxy6.contextInitialized(Unknown Source) ~[?:?]
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4766) ~[catalina.jar:9.0.56]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5230) ~[catalina.jar:9.0.56]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[catalina.jar:9.0.56]
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:726) ~[catalina.jar:9.0.56]
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:698) ~[catalina.jar:9.0.56]
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:696) ~[catalina.jar:9.0.56]
	at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:690) ~[catalina.jar:9.0.56]
	at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1889) ~[catalina.jar:9.0.56]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_202]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_202]
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) ~[tomcat-util.jar:9.0.56]
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112) ~[?:1.8.0_202]
	at org.apache.catalina.startup.HostConfig.deployDescriptors(HostConfig.java:583) ~[catalina.jar:9.0.56]
	at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:473) ~[catalina.jar:9.0.56]
	at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1618) ~[catalina.jar:9.0.56]
	at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:319) ~[catalina.jar:9.0.56]
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123) ~[catalina.jar:9.0.56]
	at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423) ~[catalina.jar:9.0.56]
	at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:366) ~[catalina.jar:9.0.56]
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:946) ~[catalina.jar:9.0.56]
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:835) ~[catalina.jar:9.0.56]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[catalina.jar:9.0.56]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1396) ~[catalina.jar:9.0.56]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1386) ~[catalina.jar:9.0.56]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_202]
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) ~[tomcat-util.jar:9.0.56]
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134) ~[?:1.8.0_202]
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:919) ~[catalina.jar:9.0.56]
	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:263) ~[catalina.jar:9.0.56]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[catalina.jar:9.0.56]
	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:432) ~[catalina.jar:9.0.56]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[catalina.jar:9.0.56]
	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:927) ~[catalina.jar:9.0.56]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[catalina.jar:9.0.56]
	at org.apache.catalina.startup.Catalina.start(Catalina.java:772) ~[catalina.jar:9.0.56]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_202]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_202]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_202]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_202]
	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:345) ~[bootstrap.jar:9.0.56]
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:476) ~[bootstrap.jar:9.0.56]

i also try copy the jar into tomcat-9.0.56\webapps\ROOT\WEB-INF\shielded-container-lib, and change compile to compileOnly
it doesn't work

and after modify bnd.bnd
`Include-Resource:\
    @salesforce-client-soap-1.2.0.jar

Private-Package:\
	com.sforce.soap.partner.*,\
	com.sforce.ws.*
`
error message shows
com.liferay.portal.kernel.log.LogSanitizerException: org.osgi.framework.BundleException: Could not resolve module: com.raritan.ci.pqm.api [1487]_  Unresolved requirement: Import-Package: com.google.appengine.api.urlfetch_ [Sanitized]
	at org.eclipse.osgi.container.Module.start(Module.java:444) ~[org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:428) ~[org.eclipse.osgi.jar:?]
	at com.liferay.portal.file.install.internal.DirectoryWatcher._startBundle(DirectoryWatcher.java:1176) [bundleFile:?]

**Comment by amusarra** [comment]
Hi @ScarleTAKE 
The salesforce bundle version you should install as a classic Liferay bundle and not as an external library. That way you shouldn't have any problems. I remind you that version 1.2.0 refers to version 47 of the Salesforce SOAP API.

**Comment by amusarra** [comment]
Hi @ScarleTAKE let me know.

**Comment by ScarleTAKE** [comment]
It's ready to use.
I rebuild a new api module
Add dependencies in build.gradle
`	compileOnly group:'it.dontesta.labs.liferay.salesforce.client.soap', name:'salesforce-client-soap', version:'1.2.0'
	compileOnly group: 'com.force.api', name: 'force-wsc', version: '47.0.0'
`
install 1.2.0.jar in gogo shell
deploy the module
it's work.

My original approach was to add it to the api module generated by service-builder
Add dependencies in build.gradle
`	compileOnly group:'it.dontesta.labs.liferay.salesforce.client.soap', name:'salesforce-client-soap', version:'1.2.0'
	compileOnly group: 'com.force.api', name: 'force-wsc', version: '47.0.0'
`
add in bnd.bnd
`	
Include-Resource:\
    @salesforce-client-soap-1.2.0.jar,\
    @force-wsc-47.0.0.jar,\
    @ST4-4.0.7.jar,\
    @commons-beanutils-1.9.4.jar,\
    @commons-collections-3.2.2.jar,\
    @jackson-mapper-asl-1.9.13.jar,\
    @jackson-core-asl-1.9.13.jar,\
    @antlr-runtime-3.5.jar,\
    @stringtemplate-3.2.1.jar,\
    @antlr-2.7.7.jar

Private-Package:\
	com.sforce.soap.partner.*,\
	com.sforce.ws.*
Import-Package: \
    !com.google.appengine.api.urlfetch.*
`
it's keep failing

The difference between the two cases is whether to install 1.2.0.jar via gogo shell
This is my first time using install 1.2.0.jar via gogo shell, I don't know why and how it works.
In theory, adding dependencies in build.gradle should already be able to use the jar file. what's different between deploy with configed build.gradle module and install via gogo shell?
if i want refresh all mudole to newest version, i always delete \osgi\state(i do not know any other better way), and i have to reinseall salesforce-client-soap-1.2.0.jar

thank you.
btw, the link in README
install http://repo1.maven.org/maven2/it/dontesta/labs/liferay/salesforce/client/soap/salesforce-client-soap/1.2.0/salesforce-client-soap-1.2.0.jar
cannot work, it should be https

again, thank you

**Comment by amusarra** [comment]
The jar of the Salesforce client is a OSGi bundle that export the Salesforce API; you must deploy tho jar as bundle OSGi via GogoShell or via deploy folder. 

You can try thi project example, where use this jar as dependency https://github.com/amusarra/salesforce-client-gogoshell-command

I will update the README file.

Can I close this issue?

Thanks.

**Comment by ScarleTAKE** [comment]
sure, thank you very much.
have a nice day.
